eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8761/eureka/,http://eureka-server3:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kaijun2004/config-repo.git
          username: kaijun2004
          password:
  rabbitmq:
    host:
    port: 5672
    username: kaijun.yuan
    password:
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: "*"